# Generated by Django 6.0 on 2025-12-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Fingerprint Device', 'verbose_name_plural': 'Fingerprint Devices'},
        ),
    ]
